version: '3.8'
services:
  redis:
    image: redis
    container_name: team-tracker-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - team-project-tracker-network

  postgres:
    image: postgres:13-alpine
    container_name: team-tracker-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789root
      POSTGRES_DB: team_tracker
    ports:
      - "5432:5432"
    volumes:
      - ../../postgres-data:/var/lib/postgresql/data
    networks:
      - team-project-tracker-network

  app:
    build: .
    container_name: team-tracker-backend
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/team_tracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456789root

    volumes:
      - ../../postgres-data:/var/lib/postgresql/data
    networks:
      - team-project-tracker-network


networks:
  team-project-tracker-network:
    driver: bridge
#
#  #    volumes:
#  #      db-data:
#  #        driver: local
#  #     networks:
#  #     team-project-tracker-network:
#  #       driver: bridge
#  #
