version: '3.8'
services:
  redis:
    image: redis
    container_name: team-tracker-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  #    networks:
  #      - team-project-tracker-network

  db:
    image: postgres
    container_name: team-tracker-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789root
      - POSTGRES_DB=tracker
    ports:
      - "3232:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
#    networks:
#      - team-project-tracker-network
#
#  app:
#    build: .
#    container_name: team-tracker-backend
#    ports:
#      - "8090:8090"
#    depends_on:
#      - db
#    environment:
#      - POSTGRES_URL=jdbc:postgresql://db:5432/tracker?createDatabaseIfNotExist=true
#      - POSTGRES_USERNAME=postgres
#      - POSTGRES_PASSWORD=123456789root
#
#    volumes:
#      - /postgres-data:/var/lib/postgresql/data
#    networks:
#      - team-project-tracker-network
#
volumes:
  postgres-data:
    driver: local
#networks:
#  team-project-tracker-network:
#    driver: bridge