version: '3.8'
services:
  app:
    image: kamran01/team-project-tracker:0.0.1
    container_name: team-tracker-backend
    ports:
      - '8080:8080'
    environment:
      URL: "jdbc:postgresql://db:5432/team_tracker"
      USERNAME: "postgres"
      PASSWORD: "123456789secret"
    networks:
      - team-project-tracker-network
    depends_on:
      - db

  db:
    image: postgres
    container_name: team-tracker-db
    restart: always
    environment:
#      - POSTGRES_INITDB_ARGS: '--auth-host=scram-sha-256 --auth-local=scram-sha-256'
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789secret
      - POSTGRES_DB=team_tracker
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../../backups/database:/var/backups
      - ./postgresql.conf:/etc/postgres/sql/postgresql.conf
    #    volumes:
    #      - C:\Program Files\PostgreSQL\16\docker-volumes\docker-volumes-db:/var/lib/postgresql/data
    networks:
      - team-project-tracker-network
volumes:
  db-data:
    driver: local
networks:
  team-project-tracker-network:
    driver: bridge
#
#  redis:
#    container_name: team-tracker-redis
#    image: 'bitnami/redis:latest'
#    restart: always
#    environment:
#      - REDIS_PASSWORD=123456789redis
#    ports:
#      - '6379:6379'
#    volumes:
#      - ../../docker-volumes/docker-volumes-redis:/bitnami/redis/data