spring:

#Database Configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://localhost:5433/team_tracker?createDatabaseIfNotExist=true
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}

  #  #Redis Configuration
  #  redis:
  #    redisson:
  #      file: classpath:redisson.yml

#JPA Configuration
  jpa:
    #    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show_sql: true

#Docker Configuration
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop

#Mail Sender Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: axmedovkamran127@gmail.com
    password: tlbxhhwcvyvnpmhf
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
          enable: true
          debug: true

#  main:
#    allow-bean-definition-overriding: true

#SQL Configuration
#  sql:
#   init:
#     mode: always
#     platform: mysql
#     schema-locations: classpath:SqlCommands/create_roles.sql
#, classpath:SqlCommands/create_Super_Admin.sql

#Security Configuration
security:
  jwt:
    secret: "AAAAB3NzaC1yc2EAAAADAQABAAAAgQDYj4ZZDmECmQ3RveM3IHmhKJmjG9AFA6m4eMj1bmhmZW1FHMPcikdKeMcThKVvfmV8soxQz64ZS"
    lifetime: 30m

#Server Port Configuration
server:
  port: 8090

#logging:
#  file:
#    name:
