spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #    url: ${POSTGRES_URL}
    #    username: ${POSTGRES_USERNAME}
    #    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    #    defer-datasource-initialization: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show_sql: true
