spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #    url: ${POSTGRES_URL}
    #    username: ${POSTGRES_USERNAME}
    #    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:3232/tracker
    username: postgres
    password: 123456789root
  jpa:
    #    defer-datasource-initialization: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show_sql: true
